---
abstract: 'obtain the REFCNT value of a referent'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  ExtUtils::CBuilder: 0
  Module::Build: 0
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-Refcount
provides:
  Devel::Refcount:
    file: lib/Devel/Refcount.pm
    version: 0.09
requires:
  Exporter: 5.57
  XSLoader: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.09
