---
name: Devel-Refcount
version: 0.03
author:
  - 'Paul Evans E<lt>leonerd@leonerd.org.ukE<gt>'
abstract: obtain the REFCNT value of a referent
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  ExtUtils::CBuilder: 0
  Test::Exception: 0
  Test::More: 0
provides:
  Devel::Refcount:
    file: lib/Devel/Refcount.pm
    version: 0.03
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
