---
name: Devel-Refcount
version: 0.06
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: obtain the REFCNT value of a referent
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  ExtUtils::CBuilder: 0
  Module::Build: 0
build_requires:
  ExtUtils::CBuilder: 0
  Module::Build: 0
  Test::Exception: 0
  Test::More: 0
provides:
  Devel::Refcount:
    file: lib/Devel/Refcount.pm
    version: 0.06
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
